[package]
name = "oracle_aggregator_pyth_lazer_rolling_integration"
edition = "2024.alpha"
version = "0.0.1"
published-at = "0x7ab17437b8abad366757ac8cec7cdf8ab483090d9d5026e45cc37f27769535e8"
# upgrade-cap = "0x6530c7152351865b169eb734286b782b7eb58018e733357abf7f777415b4c0af"

[dependencies.pyth_lazer]
git = "git@github.com:AftermathFinance/pyth-crosschain.git"
subdir = "lazer/contracts/sui"
rev = "main"

[dependencies.oracle_aggregator]
local = "../../oracle-aggregator"

[dependencies.authority_cap]
local = "../../../authority-cap/authority-cap"

[addresses]
oracle_aggregator_pyth_lazer_rolling_integration = "0x7ab17437b8abad366757ac8cec7cdf8ab483090d9d5026e45cc37f27769535e8"
